import type { Translator } from '@/lib/i18n'
import type { WorkplaceFormLabels } from './workplace-form'

export function buildWorkplaceFormLabels(t: Translator): WorkplaceFormLabels {
  return {
    sectionInfo: t('workplaces.form.sectionInfo'),
    sectionRiskAssessment: t('workplaces.form.sectionRiskAssessment'),
    sectionHazardProfile: t('workplaces.form.sectionHazardProfile'),
    sectionHazardProfileHelp: t('workplaces.form.sectionHazardProfileHelp'),
    sectionRequiredExamTypes: t('workplaces.form.sectionRequiredExamTypes'),
    sectionRequiredExamTypesHelp: t('workplaces.form.sectionRequiredExamTypesHelp'),
    sectionStatus: t('workplaces.form.sectionStatus'),
    fieldName: t('workplaces.form.fieldName'),
    fieldNamePlaceholder: t('workplaces.form.fieldNamePlaceholder'),
    fieldDepartment: t('workplaces.form.fieldDepartment'),
    fieldDescription: t('workplaces.form.fieldDescription'),
    fieldExaminationInterval: t('workplaces.form.fieldExaminationInterval'),
    fieldExaminationIntervalHelp: t('workplaces.form.fieldExaminationIntervalHelp'),
    fieldRiskSigned: t('workplaces.form.fieldRiskSigned'),
    fieldRiskSignedAt: t('workplaces.form.fieldRiskSignedAt'),
    fieldIsActive: t('workplaces.form.fieldIsActive'),
    required: t('workplaces.form.required'),
    submitCreate: t('workplaces.form.submitCreate'),
    submitUpdate: t('workplaces.form.submitUpdate'),
    submitting: t('workplaces.form.submitting'),
    cancel: t('common.cancel'),
    errorMessage: t('workplaces.form.errorMessage'),
    hazardCategory: {
      physical: t('workplaces.form.hazardCategory.physical'),
      chemical: t('workplaces.form.hazardCategory.chemical'),
      biological: t('workplaces.form.hazardCategory.biological'),
      ergonomic: t('workplaces.form.hazardCategory.ergonomic'),
      psychosocial: t('workplaces.form.hazardCategory.psychosocial'),
    },
    hazardName: {
      noise: t('workplaces.form.hazardName.noise'),
      vibrations: t('workplaces.form.hazardName.vibrations'),
      ionizingRadiation: t('workplaces.form.hazardName.ionizingRadiation'),
      electromagneticFields: t('workplaces.form.hazardName.electromagneticFields'),
      extremeTemperatures: t('workplaces.form.hazardName.extremeTemperatures'),
      lightingDeficiency: t('workplaces.form.hazardName.lightingDeficiency'),
      dust: t('workplaces.form.hazardName.dust'),
      fumes: t('workplaces.form.hazardName.fumes'),
      vapors: t('workplaces.form.hazardName.vapors'),
      solvents: t('workplaces.form.hazardName.solvents'),
      heavyMetals: t('workplaces.form.hazardName.heavyMetals'),
      acidsOrBases: t('workplaces.form.hazardName.acidsOrBases'),
      bacteria: t('workplaces.form.hazardName.bacteria'),
      viruses: t('workplaces.form.hazardName.viruses'),
      fungi: t('workplaces.form.hazardName.fungi'),
      bloodbornePathogens: t('workplaces.form.hazardName.bloodbornePathogens'),
      manualHandling: t('workplaces.form.hazardName.manualHandling'),
      repetitiveMovements: t('workplaces.form.hazardName.repetitiveMovements'),
      awkwardPostures: t('workplaces.form.hazardName.awkwardPostures'),
      screenWork: t('workplaces.form.hazardName.screenWork'),
      nightShift: t('workplaces.form.hazardName.nightShift'),
      workplaceStress: t('workplaces.form.hazardName.workplaceStress'),
      isolatedWork: t('workplaces.form.hazardName.isolatedWork'),
      violenceRisk: t('workplaces.form.hazardName.violenceRisk'),
    },
    severityLabel: t('workplaces.form.severityLabel'),
    severityLow: t('workplaces.form.severityLow'),
    severityMedium: t('workplaces.form.severityMedium'),
    severityHigh: t('workplaces.form.severityHigh'),
    notesPlaceholder: t('workplaces.form.notesPlaceholder'),
    caenSuggestionsTitle: t('workplaces.form.caenSuggestionsTitle'),
    caenSuggestionsHint: t('workplaces.form.caenSuggestionsHint'),
    caenSuggestionsApply: t('workplaces.form.caenSuggestionsApply'),
    caenSuggestionsApplied: t('workplaces.form.caenSuggestionsApplied'),
  }
}
